name: dog_meet_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.11.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^0.7.4
  font_awesome_flutter: ^9.0.0
  ionicons: ^0.1.2
  animations: ^2.0.0
  lottie: ^1.0.1
  sliding_sheet: ^0.5.0
  bubble_tab_indicator: ^0.1.6
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.5


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/json/

  fonts:
  - family: Gibson
    fonts:
    - asset: assets/fonts/gibson/GibsonRegular.ttf
      weight: 400
    - asset: assets/fonts/gibson/GibsonSemiBd.ttf
      weight: 600
    - asset: assets/fonts/gibson/GibsonBold.ttf
      weight: 700


  - family: Archivo
    fonts:
      - asset: assets/fonts/archivo/Archivo-Regular.ttf
        weight: 400
      - asset: assets/fonts/archivo/Archivo-Italic.ttf
        style: italic
        weight: 400
      - asset: assets/fonts/archivo/Archivo-Medium.ttf
        weight: 500
      - asset: assets/fonts/archivo/Archivo-MediumItalic.ttf
        style: italic
        weight: 500
      - asset: assets/fonts/archivo/Archivo-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/archivo/Archivo-SemiBoldItalic.ttf
        style: italic
        weight: 600
      - asset: assets/fonts/archivo/Archivo-Bold.ttf
        weight: 700
      - asset: assets/fonts/archivo/Archivo-BoldItalic.ttf
        style: italic
        weight: 700

